package com.armsx2

import kr.co.iefriends.pcsx2.NativeApp
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * On-device contract tests for the tar+zstd JNI decoder (NativeApp.zstdDecoder*). Fixtures are
 * embedded hex produced by the zstd CLI, because there is no zstd on the device: OK is a 294-byte
 * frame decompressing to 153,600 patterned bytes, EMPTY is a valid zero-length frame, and BIGWIN
 * declares window log 31, which exceeds the bridge's 27 cap.
 */
class ZstdBridgeInstrumentedTest {
    companion object {
        // (the hex constants live at the bottom of this file, generated by the zstd CLI)

        private val PLAIN_SIZE: Int = 256 * 600 // 153600 bytes of bytes(range(256)) * 600

        private fun hexToBytes(hex: String): ByteArray =
            ByteArray(hex.length / 2) { i ->
                ((Character.digit(hex[i * 2], 16) shl 4) or Character.digit(hex[i * 2 + 1], 16)).toByte()
            }

        private val OK = hexToBytes(OK_HEX)
        private val EMPTY = hexToBytes(EMPTY_HEX)
        private val BIGWIN = hexToBytes(BIGWIN_HEX)

        private const val STATUS_CONSUMED = 0
        private const val STATUS_PRODUCED = 1
        private const val STATUS_DONE = 2

        /** Drives [NativeApp.zstdDecoderDecode] until the input is consumed or the call errors. */
        private fun feed(
            handle: Long,
            input: ByteArray,
            outCap: Int = 256 * 1024,
        ): DecodeResult {
            val status = LongArray(3)
            val out = ByteArray(outCap)
            val plain = StringBuilder()
            var inPos = 0
            while (true) {
                val inLen = minOf(64 * 1024, input.size - inPos)
                val produced = NativeApp.zstdDecoderDecode(
                    handle, input, inPos, inLen, out, 0, out.size, status,
                )
                if (produced < 0) return DecodeResult(error = true, plain = plain.toString())
                inPos += status[STATUS_CONSUMED].toInt()
                if (produced > 0) plain.append(String(out, 0, produced, Charsets.ISO_8859_1))
                if (status[STATUS_DONE] == 1L) {
                    return DecodeResult(done = true, plain = plain.toString(), consumedAll = inPos >= input.size)
                }
                if (inPos >= input.size) {
                    // All input given, frame not yet complete: emulate the caller reaching EOF.
                    return DecodeResult(done = false, plain = plain.toString(), consumedAll = true)
                }
            }
        }

        private data class DecodeResult(
            val done: Boolean = false,
            val error: Boolean = false,
            val consumedAll: Boolean = false,
            val plain: String = "",
        )
    }

    @Before
    fun requireNativeBinary() {
        org.junit.Assert.assertFalse("emucore not loaded on this device", NativeApp.hasNoNativeBinary)
    }

    @Test
    fun createRejectsInvalidCaps() {
        assertEquals(0L, NativeApp.zstdDecoderCreate(0))
        assertEquals(0L, NativeApp.zstdDecoderCreate(-1))
        assertEquals(0L, NativeApp.zstdDecoderCreate(16L * 1024 * 1024 * 1024 + 1))
    }

    @Test
    fun validFrameStreamsAcrossChunkBoundaries() {
        val handle = NativeApp.zstdDecoderCreate(16L * 1024 * 1024 * 1024)
        assertNotEquals(0L, handle)
        try {
            val result = feed(handle, OK)
            assertTrue("decode errored", !result.error)
            assertTrue("frame did not complete", result.done)
            assertTrue("trailing input not detected", result.consumedAll)
            assertEquals(PLAIN_SIZE, result.plain.length)
            // Spot-check the pattern survived: first 300 bytes and the tail.
            val expectedFirst = (0..255).map { (it and 0xff).toChar() }.joinToString("")
            assertTrue(result.plain.startsWith(expectedFirst.substring(0, 256)))
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun decodeAfterFrameCompletionPoisons() {
        val handle = NativeApp.zstdDecoderCreate(1 shl 20)
        try {
            val status = LongArray(3)
            val out = ByteArray(1024)
            val first = NativeApp.zstdDecoderDecode(handle, EMPTY, 0, EMPTY.size, out, 0, out.size, status)
            assertTrue(first >= 0)
            assertEquals(1L, status[2])
            assertEquals(-1, NativeApp.zstdDecoderDecode(handle, EMPTY, 0, EMPTY.size, out, 0, out.size, status))
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun oversizedWindowRejected() {
        val handle = NativeApp.zstdDecoderCreate(1 shl 30)
        try {
            val result = feed(handle, BIGWIN)
            assertTrue("window-log-31 frame must be rejected", result.error)
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun corruptedFramePoisonsHandle() {
        val corrupt = OK.copyOf().also { it[it.size / 2] = (it[it.size / 2].toInt() xor 0x5a).toByte() }
        val handle = NativeApp.zstdDecoderCreate(1 shl 30)
        try {
            val result = feed(handle, corrupt)
            assertTrue("corruption must be detected", result.error)
            // Poisoned handles stay dead:
            val status = LongArray(3)
            assertEquals(-1, NativeApp.zstdDecoderDecode(handle, OK, 0, OK.size, ByteArray(1024), 0, 1024, status))
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun truncatedFrameReportsIncompleteAtEof() {
        val truncated = OK.copyOf(OK.size / 2)
        val handle = NativeApp.zstdDecoderCreate(1 shl 30)
        try {
            val result = feed(handle, truncated)
            assertTrue(!result.error)
            assertTrue(!result.done) // EOF with no frame end: the wrapper turns this into an error
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun trailingBytesAfterFrameRejected() {
        val trailing = OK + OK
        val handle = NativeApp.zstdDecoderCreate(1 shl 30)
        try {
            val result = feed(handle, trailing)
            assertTrue("second frame must be rejected", result.error)
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun outputCapEnforced() {
        val handle = NativeApp.zstdDecoderCreate(1024) // plain size is far larger
        try {
            val result = feed(handle, OK)
            assertTrue("output cap must trip", result.error)
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }

    @Test
    fun zeroHandleDestroyIsSafe() {
        NativeApp.zstdDecoderDestroy(0)
    }

    @Test
    fun decodeWithBadWindowsRejected() {
        val handle = NativeApp.zstdDecoderCreate(1 shl 20)
        try {
            val status = LongArray(3)
            val out = ByteArray(1024)
            assertEquals(-1, NativeApp.zstdDecoderDecode(handle, OK, -1, OK.size, out, 0, out.size, status))
            assertEquals(-1, NativeApp.zstdDecoderDecode(handle, OK, 0, OK.size + 1, out, 0, out.size, status))
            assertEquals(-1, NativeApp.zstdDecoderDecode(handle, OK, 0, OK.size, out, 0, out.size, LongArray(2)))
        } finally {
            NativeApp.zstdDecoderDestroy(handle)
        }
    }
}

private const val OK_HEX =
    "28b52ffda4005802005c08000410000102030405060708090a0b0c0d0e0f10111213141516171819" +
        "1a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f4041" +
        "42434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f60616263646566676869" +
        "6a6b6c6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f9091" +
        "92939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9" +
        "babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1" +
        "e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff010000fdfe03f99a0245" +
        "000008000100fcd70e84ccf06803"

private const val EMPTY_HEX =
    "28b52ffd240001000099e9d851"

private const val BIGWIN_HEX =
    "28b52ffd04a85c08000410000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c" +
        "1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f4041424344" +
        "45464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c" +
        "6d6e6f707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f9091929394" +
        "95969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbc" +
        "bdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4" +
        "e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff010000fdfe03f99a0245000008" +
        "000100fcd70e84ccf06803"
