# Turns files from bin/resources into a C++ translation unit, so a build can
# carry them instead of reading them out of a resources directory at runtime.
#
# Run in script mode:
#   cmake -DOUT=<file.cpp> -DROOT=<resources dir> -DLIST=<file> -P EmbedResources.cmake
#
# LIST is a file with one entry per line. An entry is either a path relative to
# ROOT, or "name=/absolute/path" for something that is not in the resources
# directory - a file the build downloaded, say. Either way the name is what the
# lookup takes: the same string the readers ask for. A file rather than a -D list because a CMake list on a command
# line has to survive two levels of escaping, and does not.

if(NOT DEFINED OUT OR NOT DEFINED ROOT OR NOT DEFINED LIST)
	message(FATAL_ERROR "EmbedResources.cmake needs OUT, ROOT and LIST")
endif()

file(STRINGS "${LIST}" FILES)
if(NOT FILES)
	message(FATAL_ERROR "EmbedResources.cmake: ${LIST} is empty")
endif()

set(blobs "")
set(table "")
set(index 0)

foreach(entry IN LISTS FILES)
	if(entry MATCHES "^([^=]+)=(.+)$")
		set(rel "${CMAKE_MATCH_1}")
		set(path "${CMAKE_MATCH_2}")
	else()
		set(rel "${entry}")
		set(path "${ROOT}/${entry}")
	endif()
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "EmbedResources.cmake: missing ${path}")
	endif()
	file(READ "${path}" hex HEX)
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
	string(APPEND blobs "const unsigned char s_blob_${index}[] = {${bytes}};\n")
	string(APPEND table "\t{\"${rel}\", s_blob_${index}, sizeof(s_blob_${index})},\n")
	math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUT}" "// Generated by cmake/EmbedResources.cmake - do not edit.

#include \"EmbeddedResources.h\"

#include <cstring>

namespace
{
${blobs}
	struct Entry
	{
		const char* name;
		const unsigned char* data;
		size_t size;
	};

	const Entry s_entries[] = {
${table}	};
} // namespace

std::optional<std::string> EmbeddedResources::Read(const char* filename)
{
	for (const Entry& entry : s_entries)
	{
		if (std::strcmp(entry.name, filename) == 0)
			return std::string(reinterpret_cast<const char*>(entry.data), entry.size);
	}

	return std::nullopt;
}
")
