// GENERATED by captures/vumadd/gen_autocases.py from a capture taken on an
// SCPH-90000 (hw-run1.out, byte-identical to hw-run2.out). Do not edit by hand.
//
// VU0 macro-mode MADDA/MSUBA. Each row seeds ACC.x, vfs.x and vft.x, issues one
// accumulate, and records the ACC.x the console produced. Eight of the ten rows
// separate a fused multiply-accumulate from two separate roundings; see
// vu_madd_contract_console_tests.cpp.
#pragma once
#include <common/Pcsx2Types.h>

namespace console_vumadd {

struct VuMaddCase {
	u32 acc, fs, ft;   // seeded into ACC.x, vf(fs).x, vf(ft).x
	bool sub;          // true = VMSUBA, false = VMADDA
	u32 acc_out;       // ACC.x on the console
	const char* what;
};

inline constexpr VuMaddCase kVuMaddCases[] = {
	{0x40000000u, 0x3F800000u, 0x3F800000u, true, 0x3F800000u, "CONTROL identity: 2.0 - 1.0*1.0, every model says 3F800000"},
	{0x40490FDBu, 0x00000000u, 0x00000000u, true, 0x40490FDBu, "CONTROL liveness: pi - 0*0, must differ from the row above"},
	{0x3F800001u, 0x3EAAAAABu, 0x40400000u, true, 0x34000000u, "MSUBA (1+2^-23) - (1/3)*3 fused 33C00000 | RTZ 34000000 | RTZ-1ulp 34400000"},
	{0xBF800001u, 0x3EAAAAABu, 0x40400000u, false, 0xB4000000u, "MADDA -(1+2^-23) + (1/3)*3 mirror of the row above"},
	{0x3F800001u, 0x40400000u, 0x3EAAAAABu, true, 0x34000000u, "MSUBA operand order swapped -- the EE multiplier is not commutative"},
	{0x3F800000u, 0x3EAAAAABu, 0x40400000u, true, 0x00000000u, "MSUBA 1.0 - (1/3)*3 fused B3000000 | two-rounding 00000000"},
	{0x3F800000u, 0x40400000u, 0x3EAAAAABu, true, 0x00000000u, "MSUBA 1.0 - 3*(1/3) operand order swapped"},
	{0xBF800000u, 0x3EAAAAABu, 0x40400000u, false, 0x00000000u, "MADDA -1.0 + (1/3)*3 fused 33000000 | two-rounding 00000000"},
	{0x3F800002u, 0x3F800001u, 0x3F800001u, true, 0x00000000u, "MSUBA (1+2^-22) - (1+2^-23)^2 exact product 1+2^-22+2^-46"},
	{0x40000001u, 0x3FB504F3u, 0x3FB504F3u, true, 0x34C00000u, "MSUBA (2+2^-22) - sqrt2^2 exact product 1.99999982"},
};

} // namespace console_vumadd
