// GENERATED by captures/vuflow/gen_autocases.py from a capture taken on an
// SCPH-90000 (hw-run1.out, byte-identical to hw-run2.out). Do not edit by hand.
//
// The VU FMAC where a result lands strictly below 2^-126. Each row seeds
// fs/ft/acc into all four lanes of vf1/vf2/vf3, runs
//
//     vadda.xyzw $ACC, $vf3, $vf7      ; vf7 is zero, so ACC = acc
//     <op>.xyzw  $vf4, $vf1, $vf2
//
// and records vf4, the MAC flag and the status flag, the status flag having
// been cleared before the pair.
//
// A result below 2^-126 that is not zero is exactly k*2^-149 with
// 1 <= k < 2^23, so flushing it, encoding it and leaving the mantissa where
// normalisation put it are three different words. Of the 51 rows that
// separate all three, 48 say mantissa-in-place -- every ADD, SUB, MADD and
// MSUB -- and 3 say flush, every one of them a MUL. None says the true
// value. That is the EE FPU's law exactly (captures/fpuflow).
//
// bad_interp / bad_jit are not from the console: they are what this tree
// currently fails to reproduce, per column, regenerated from the test
// binary's own dump. Clearing a bit is how a fix lands.
#pragma once
#include <common/Pcsx2Types.h>

namespace console_vuflow {

enum VuFlowOp { VF_ADD, VF_SUB, VF_MUL, VF_MADD, VF_MSUB };

// Columns a case can be wrong in, independently.
enum { VFB_VALUE = 1, VFB_MAC = 2, VFB_STAT = 4 };

struct VuFlowCase {
	u8 op;
	u32 fs, ft, acc;      // seeded into all four lanes of vf1 / vf2 / vf3
	u32 out;              // vf4 on the console, all four lanes
	u16 mac, stat;        // VI17 and VI16 on the console
	u8 bad_interp, bad_jit;
	const char* what;
};

inline constexpr VuFlowCase kVuFlowCases[] = {
	{VF_ADD,  0x3F800000u, 0x3F800000u, 0x00000000u, 0x40000000u, 0x0000u, 0x0040u, 0, 0, "G ctl plumbing 1.0+1.0 -> 40000000"},
	{VF_ADD,  0x3F800000u, 0xBF800000u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl liveness 1.0-1.0: value AND MAC must differ from the row above"},
	{VF_SUB,  0x00800001u, 0x00800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A sub +0x1*2^-149"},
	{VF_ADD,  0x00800001u, 0x80800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A add +0x1*2^-149"},
	{VF_SUB,  0x80800001u, 0x80800000u, 0x00000000u, 0x80000000u, 0x0FFFu, 0x01C7u, 0, 6, "A sub -0x1*2^-149"},
	{VF_SUB,  0x00800002u, 0x00800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A sub +0x2*2^-149"},
	{VF_ADD,  0x00800002u, 0x80800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A add +0x2*2^-149"},
	{VF_SUB,  0x80800002u, 0x80800000u, 0x00000000u, 0x80000000u, 0x0FFFu, 0x01C7u, 0, 6, "A sub -0x2*2^-149"},
	{VF_SUB,  0x00800003u, 0x00800000u, 0x00000000u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x3*2^-149"},
	{VF_ADD,  0x00800003u, 0x80800000u, 0x00000000u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x3*2^-149"},
	{VF_SUB,  0x80800003u, 0x80800000u, 0x00000000u, 0x80400000u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x3*2^-149"},
	{VF_SUB,  0x00800005u, 0x00800000u, 0x00000000u, 0x00200000u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x5*2^-149"},
	{VF_ADD,  0x00800005u, 0x80800000u, 0x00000000u, 0x00200000u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x5*2^-149"},
	{VF_SUB,  0x80800005u, 0x80800000u, 0x00000000u, 0x80200000u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x5*2^-149"},
	{VF_SUB,  0x00800007u, 0x00800000u, 0x00000000u, 0x00600000u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x7*2^-149"},
	{VF_ADD,  0x00800007u, 0x80800000u, 0x00000000u, 0x00600000u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x7*2^-149"},
	{VF_SUB,  0x80800007u, 0x80800000u, 0x00000000u, 0x80600000u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x7*2^-149"},
	{VF_SUB,  0x0080000Fu, 0x00800000u, 0x00000000u, 0x00700000u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0xf*2^-149"},
	{VF_ADD,  0x0080000Fu, 0x80800000u, 0x00000000u, 0x00700000u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0xf*2^-149"},
	{VF_SUB,  0x8080000Fu, 0x80800000u, 0x00000000u, 0x80700000u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0xf*2^-149"},
	{VF_SUB,  0x00800101u, 0x00800000u, 0x00000000u, 0x00008000u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x101*2^-149"},
	{VF_ADD,  0x00800101u, 0x80800000u, 0x00000000u, 0x00008000u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x101*2^-149"},
	{VF_SUB,  0x80800101u, 0x80800000u, 0x00000000u, 0x80008000u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x101*2^-149"},
	{VF_SUB,  0x00923456u, 0x00800000u, 0x00000000u, 0x0011A2B0u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x123456*2^-149"},
	{VF_ADD,  0x00923456u, 0x80800000u, 0x00000000u, 0x0011A2B0u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x123456*2^-149"},
	{VF_SUB,  0x80923456u, 0x80800000u, 0x00000000u, 0x8011A2B0u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x123456*2^-149"},
	{VF_SUB,  0x00955555u, 0x00800000u, 0x00000000u, 0x002AAAA8u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x155555*2^-149"},
	{VF_ADD,  0x00955555u, 0x80800000u, 0x00000000u, 0x002AAAA8u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x155555*2^-149"},
	{VF_SUB,  0x80955555u, 0x80800000u, 0x00000000u, 0x802AAAA8u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x155555*2^-149"},
	{VF_SUB,  0x00AAAAABu, 0x00800000u, 0x00000000u, 0x002AAAACu, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x2aaaab*2^-149"},
	{VF_ADD,  0x00AAAAABu, 0x80800000u, 0x00000000u, 0x002AAAACu, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x2aaaab*2^-149"},
	{VF_SUB,  0x80AAAAABu, 0x80800000u, 0x00000000u, 0x802AAAACu, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x2aaaab*2^-149"},
	{VF_SUB,  0x00C00000u, 0x00800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A sub +0x400000*2^-149"},
	{VF_ADD,  0x00C00000u, 0x80800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 6, "A add +0x400000*2^-149"},
	{VF_SUB,  0x80C00000u, 0x80800000u, 0x00000000u, 0x80000000u, 0x0FFFu, 0x01C7u, 0, 6, "A sub -0x400000*2^-149"},
	{VF_SUB,  0x00C00001u, 0x00800000u, 0x00000000u, 0x00000002u, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x400001*2^-149"},
	{VF_ADD,  0x00C00001u, 0x80800000u, 0x00000000u, 0x00000002u, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x400001*2^-149"},
	{VF_SUB,  0x80C00001u, 0x80800000u, 0x00000000u, 0x80000002u, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x400001*2^-149"},
	{VF_SUB,  0x00D55555u, 0x00800000u, 0x00000000u, 0x002AAAAAu, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x555555*2^-149"},
	{VF_ADD,  0x00D55555u, 0x80800000u, 0x00000000u, 0x002AAAAAu, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x555555*2^-149"},
	{VF_SUB,  0x80D55555u, 0x80800000u, 0x00000000u, 0x802AAAAAu, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x555555*2^-149"},
	{VF_SUB,  0x00FFFFFFu, 0x00800000u, 0x00000000u, 0x007FFFFEu, 0x0F0Fu, 0x0145u, 0, 7, "A sub +0x7fffff*2^-149"},
	{VF_ADD,  0x00FFFFFFu, 0x80800000u, 0x00000000u, 0x007FFFFEu, 0x0F0Fu, 0x0145u, 0, 7, "A add +0x7fffff*2^-149"},
	{VF_SUB,  0x80FFFFFFu, 0x80800000u, 0x00000000u, 0x807FFFFEu, 0x0FFFu, 0x01C7u, 0, 7, "A sub -0x7fffff*2^-149"},
	{VF_SUB,  0x01000000u, 0x00FFFFFDu, 0x00000000u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "B sub +0x3*2^-149"},
	{VF_SUB,  0x01000000u, 0x00FFFFFBu, 0x00000000u, 0x00200000u, 0x0F0Fu, 0x0145u, 0, 7, "B sub +0x5*2^-149"},
	{VF_SUB,  0x01000000u, 0x00EDCBAAu, 0x00000000u, 0x0011A2B0u, 0x0F0Fu, 0x0145u, 0, 7, "B sub +0x123456*2^-149"},
	{VF_SUB,  0x01000000u, 0x00800001u, 0x00000000u, 0x007FFFFEu, 0x0F0Fu, 0x0145u, 0, 7, "B sub +0x7fffff*2^-149"},
	{VF_SUB,  0x08000000u, 0x07FFFFFDu, 0x00000000u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "C sub +3*2^-136"},
	{VF_SUB,  0x08000000u, 0x07FFFFFBu, 0x00000000u, 0x00200000u, 0x0F0Fu, 0x0145u, 0, 7, "C sub +5*2^-136"},
	{VF_MSUB, 0x00800000u, 0x3F800000u, 0x00800003u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "D msub +0x3*2^-149"},
	{VF_MADD, 0x80800000u, 0x3F800000u, 0x00800003u, 0x00400000u, 0x0F0Fu, 0x01C5u, 0, 7, "D madd +0x3*2^-149"},
	{VF_MADD, 0x00800000u, 0x3F800000u, 0x80800003u, 0x80400000u, 0x0FFFu, 0x01C7u, 0, 7, "D madd -0x3*2^-149"},
	{VF_MSUB, 0x00800000u, 0x3F800000u, 0x00923456u, 0x0011A2B0u, 0x0F0Fu, 0x0145u, 0, 7, "D msub +0x123456*2^-149"},
	{VF_MADD, 0x80800000u, 0x3F800000u, 0x00923456u, 0x0011A2B0u, 0x0F0Fu, 0x01C5u, 0, 7, "D madd +0x123456*2^-149"},
	{VF_MADD, 0x00800000u, 0x3F800000u, 0x80923456u, 0x8011A2B0u, 0x0FFFu, 0x01C7u, 0, 7, "D madd -0x123456*2^-149"},
	{VF_MSUB, 0x00800000u, 0x3F800000u, 0x00FFFFFFu, 0x007FFFFEu, 0x0F0Fu, 0x0145u, 0, 7, "D msub +0x7fffff*2^-149"},
	{VF_MADD, 0x80800000u, 0x3F800000u, 0x00FFFFFFu, 0x007FFFFEu, 0x0F0Fu, 0x01C5u, 0, 7, "D madd +0x7fffff*2^-149"},
	{VF_MADD, 0x00800000u, 0x3F800000u, 0x80FFFFFFu, 0x807FFFFEu, 0x0FFFu, 0x01C7u, 0, 7, "D madd -0x7fffff*2^-149"},
	{VF_MUL,  0x00C00000u, 0x3E800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul 1.5*2^-128"},
	{VF_MUL,  0x00A00000u, 0x3E800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul 1.25*2^-128"},
	{VF_MUL,  0x00C00000u, 0x3D800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul 1.5*2^-130"},
	{VF_MUL,  0x00800000u, 0x3E800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul 2^-128 (k a power of two: coincidence control)"},
	{VF_MUL,  0x00FFFFFFu, 0x3F000000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul off-grid (needs 24 bits)"},
	{VF_MUL,  0x00800000u, 0x00800000u, 0x00000000u, 0x00000000u, 0x0F0Fu, 0x0145u, 0, 0, "E mul 2^-252 (far below)"},
	{VF_SUB,  0x01800000u, 0x017FFFFDu, 0x00000000u, 0x00400000u, 0x0F0Fu, 0x0145u, 0, 7, "X sub d=2 k=0x3 (mask reaches it)"},
	{VF_SUB,  0x02000000u, 0x01FFFFFBu, 0x00000000u, 0x00200000u, 0x0F0Fu, 0x0145u, 0, 7, "X sub d=3 k=0x5 (mask reaches it)"},
	{VF_SUB,  0x04800000u, 0x046DCBAAu, 0x00000000u, 0x0291A2B0u, 0x0000u, 0x0040u, 0, 0, "X sub d=8 k=0x123456 (mask reaches it)"},
	{VF_SUB,  0x00800000u, 0x00800000u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl exact +0 cancellation"},
	{VF_ADD,  0x00800000u, 0x80800000u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl exact +0 add"},
	{VF_SUB,  0x01000000u, 0x00800000u, 0x00000000u, 0x00800000u, 0x0000u, 0x0040u, 0, 0, "G ctl result == 2^-126 exactly"},
	{VF_ADD,  0x00400000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl denormal operand + 0"},
	{VF_MUL,  0x3F800000u, 0x00000001u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl denormal operand mul"},
	{VF_SUB,  0x00000003u, 0x00000001u, 0x00000000u, 0x00000000u, 0x000Fu, 0x0041u, 0, 0, "G ctl two denormal operands"},
};

inline constexpr int kVuFlowCaseCount = 74;

// Column-cells each engine currently gets wrong, summed over the table.
inline constexpr int kVuFlowBadInterp = 0;
inline constexpr int kVuFlowBadJit = 168;

} // namespace console_vuflow
