// SPDX-FileCopyrightText: 2026 yaps2 Dev Team
// SPDX-License-Identifier: GPL-3.0+

// VIF unpack differential tests — arm64 NEON unpackers vs the scalar oracle.
//
// The VIF UNPACK command streams packed vertex data from the VIF FIFO into VU
// memory, expanding it to quadwords on the way and optionally masking, offsetting
// or skipping individual lanes. Two NEON code generators implement it on arm64,
// and until now neither had any test coverage at all:
//
//   VifUnpackNEON_Dynarec (Vif_Dynarec.cpp)  — the fast path. Compiles one
//       routine per (format, mask, mode, cycle) combination with the whole
//       num-loop unrolled inside it. Reached via dVifUnpack<idx>().
//   VifUnpackNEON_Simple  (Vif_UnpackNEON.cpp) — the per-cycle callees the
//       "interpreter" path dispatches through. Reached via _nVifUnpack(), and
//       generated by VifUnpackSSE_Init().
//
// Note that _nVifUnpack is only nominally an interpreter on arm64: for mode 0 it
// calls the NEON routines above, so using it as the oracle would compare our own
// codegen against our own codegen. The real oracle here is VIFfuncTable
// (Vif_Unpack.cpp) — the UNPACK_S / UNPACK_V2 / UNPACK_V4 / UNPACK_V4_5 template
// family. That is plain scalar C++, architecture-neutral, and shared verbatim
// with upstream PCSX2, so it is independent of everything under test.
// ReferenceUnpack below drives it with the same addressing _nVifUnpackLoop uses.
//
// ---------------------------------------------------------------------------
// The W lane of V2_32 and the V3_* formats is deliberately NOT compared.
//
// Both NEON generators zero the W lane in cases the scalar table does not:
// V2_32 does it when IsAligned, V3_32/V3_8 when UnpkLoopIteration != IsAligned,
// V3_16 on a qword boundary. The source calls this "tested on ps2", and the x86
// SSE generator does exactly the same thing (Vif_UnpackSSE.cpp), so it is an
// intentional accuracy refinement in the generators rather than a divergence we
// introduced. Meanwhile Vif_Unpack.cpp routes V3 through UNPACK_V4 on purpose —
// "confirmed real hardware behavior that games such as Ape Escape 3 depend on"
// — because the W field is normally overwritten by the following unpack anyway.
//
// Rather than re-derive the generators' iteration arithmetic in the test (which
// would make the assertion tautological), those formats compare X/Y/Z against
// the oracle and leave W to the dedicated AlignedV2_32 test below, which asserts
// the one W-lane fact that is independently checkable from the spec.
// X/Y/Z is where the sign-extension, lane-duplication and masking logic lives,
// so the formats are still meaningfully covered.

// Vif_Dynarec.h pulls in Vif_HashBucket.h, which uses pxFailRel/DevCon without
// including their headers itself — so these have to come first.
#include "common/Assertions.h"
#include "common/Console.h"
#include "common/Pcsx2Types.h"

#include "Vif.h"
#include "Vif_Dma.h"
#include "Vif_Dynarec.h"
#include "Vif_Unpack.h"
#include "VU.h"

#include "harness/RecompilerTestEnvironment.h"

#include <gtest/gtest.h>

#include <cstring>
#include <string>
#include <vector>

namespace {

// UNPACK command bytes are 0b0110_0000 | (vn << 2) | vl, with bit 4 (0x10)
// selecting the masked variant. These are the vn/vl halves; MakeCmd adds the
// 0x60 base and the mask bit.
enum UpkFormat : u8
{
	S_32  = 0x00, S_16  = 0x01, S_8  = 0x02,
	V2_32 = 0x04, V2_16 = 0x05, V2_8 = 0x06,
	V3_32 = 0x08, V3_16 = 0x09, V3_8 = 0x0a,
	V4_32 = 0x0c, V4_16 = 0x0d, V4_8 = 0x0e, V4_5 = 0x0f,
};

constexpr u8 MakeCmd(UpkFormat fmt, bool masked)
{
	return static_cast<u8>(0x60 | fmt | (masked ? 0x10 : 0x00));
}

// The generators zero W for these; the scalar table does not. See header.
constexpr bool HasDivergentWLane(UpkFormat fmt)
{
	return fmt == V2_32 || fmt == V3_32 || fmt == V3_16 || fmt == V3_8;
}

constexpr u32 VuMemSize(int idx) { return idx ? 0x4000u : 0x1000u; }

u8* VuMem(int idx) { return reinterpret_cast<u8*>(vuRegs[idx].Mem); }

// Mirrors the static getVUptr in Vif_Unpack.cpp.
u32* VuPtr(int idx, u32 offset)
{
	return reinterpret_cast<u32*>(VuMem(idx) + (offset & (idx ? 0x3ff0 : 0xff0)));
}

vifStruct& Vif(int idx) { return idx ? vif1 : vif0; }
VIFregisters& VifRegs(int idx) { return idx ? vif1Regs : vif0Regs; }

// A non-zero, non-repeating fill so that lanes the unpack is supposed to leave
// alone (write-protect masks, skipped cycles) are distinguishable from lanes it
// zeroed or wrote. A zero fill would hide exactly those bugs.
void FillVuMemPattern(int idx)
{
	u8* mem = VuMem(idx);
	const u32 size = VuMemSize(idx);
	for (u32 i = 0; i < size; i += 4)
	{
		const u32 word = 0xA5A50000u ^ (i * 2654435761u);
		std::memcpy(mem + i, &word, sizeof(word));
	}
}

struct UnpackCase
{
	const char* name;
	int idx;             // 0 = VIF0 (4 KB VU mem), 1 = VIF1 (16 KB)
	UpkFormat fmt;
	bool masked;
	u8 usn;              // unsigned flag; only meaningful for the 8/16-bit formats
	u32 num;             // quadwords to write (1..256)
	u8 cl, wl;           // CYCLE register: cl < wl fills, cl > wl skips
	u32 mode;            // MODE register: 0 normal, 1 offset, 2 difference, 3 set-row
	u32 mask;            // MASK register: 2 bits per lane per cycle
	u32 addr;            // tag.addr, the VU-memory write cursor
	u8 start_aligned;
};

// Row/col seeds. Distinct, non-zero and not equal to each other so a test can
// tell "took the row" from "took the col" from "kept the data".
constexpr u32 kRow[4] = {0x11111111u, 0x22222222u, 0x33333333u, 0x44444444u};
constexpr u32 kCol[4] = {0x55555555u, 0x66666666u, 0x77777777u, 0x78888888u};

void SeedVifState(const UnpackCase& c)
{
	vifStruct& vif = Vif(c.idx);
	VIFregisters& regs = VifRegs(c.idx);

	vif.cmd = MakeCmd(c.fmt, c.masked);
	vif.usn = c.usn;
	vif.cl = 0; // _nVifUnpackLoop asserts this
	vif.tag.addr = c.addr;
	vif.start_aligned = c.start_aligned;

	for (int i = 0; i < 4; i++)
	{
		vif.MaskRow._u32[i] = kRow[i];
		vif.MaskCol._u32[i] = kCol[i];
	}

	regs.num = c.num;
	regs.cycle.cl = c.cl;
	regs.cycle.wl = c.wl;
	regs.mode = c.mode;
	regs.mask = c.mask;

	// Guest-visible row/col mirrors. The unpack paths read vif.MaskRow/MaskCol
	// rather than these, but keep them consistent so the state is realistic.
	regs.r0 = kRow[0]; regs.r1 = kRow[1]; regs.r2 = kRow[2]; regs.r3 = kRow[3];
	regs.c0 = kCol[0]; regs.c1 = kCol[1]; regs.c2 = kCol[2]; regs.c3 = kCol[3];
}

// isFill as nVifUnpack computes it before dispatching (Vif_Unpack.cpp).
bool ComputeIsFill(const UnpackCase& c)
{
	const uint wl = c.wl ? c.wl : 256;
	return c.cl < wl;
}

// The oracle: _nVifUnpackLoop's addressing, always dispatching through the
// scalar VIFfuncTable instead of the NEON per-cycle callees.
void ReferenceUnpack(const UnpackCase& c, const u8* data)
{
	vifStruct& vif = Vif(c.idx);
	VIFregisters& regs = VifRegs(c.idx);

	const bool isFill = ComputeIsFill(c);
	const int usn = !!vif.usn;
	const int upkNum = vif.cmd & 0x1f;
	const u8 vSize = nVifT[upkNum & 0x0f];
	const int skipSize = (regs.cycle.cl - regs.cycle.wl) * 16;

	// _nVifUnpackLoop indexes [idx][doMode ? mode : 0][...]; with doMode being
	// !!mode that is just mode.
	const UNPACKFUNCTYPE ft = VIFfuncTable[c.idx][regs.mode & 3][(usn * 2 * 16) + upkNum];

	do
	{
		ft(VuPtr(c.idx, vif.tag.addr), data);

		vif.tag.addr += 16;
		--regs.num;
		++vif.cl;

		if (isFill)
		{
			if (vif.cl <= regs.cycle.cl)
				data += vSize;
			else if (vif.cl == regs.cycle.wl)
				vif.cl = 0;
		}
		else
		{
			data += vSize;
			if (vif.cl >= regs.cycle.wl)
			{
				vif.tag.addr += skipSize;
				vif.cl = 0;
			}
		}
	} while (regs.num);
}

// Deterministic source bytes. Values are spread across the full range so that
// sign-extension bugs in the 8/16-bit formats change the result.
std::vector<u8> MakeSourceData(size_t bytes)
{
	std::vector<u8> data(bytes + 64, 0); // slack: V3 reads can overrun the last element
	for (size_t i = 0; i < data.size(); i++)
		data[i] = static_cast<u8>((i * 37) ^ 0x8Cu);
	return data;
}

struct RunResult
{
	std::vector<u8> mem;
	u128 row;
};

enum class Path { Reference, InterpreterNeon, Dynarec };

RunResult RunPath(const UnpackCase& c, const std::vector<u8>& data, Path path)
{
	FillVuMemPattern(c.idx);
	SeedVifState(c);

	const bool isFill = ComputeIsFill(c);
	switch (path)
	{
		case Path::Reference:
			ReferenceUnpack(c, data.data());
			break;
		case Path::InterpreterNeon:
			_nVifUnpack(c.idx, data.data(), VifRegs(c.idx).mode, isFill);
			break;
		case Path::Dynarec:
			// Recompile from scratch so each case exercises dVifCompile rather
			// than inheriting a block another case happened to key-match.
			//
			// resetNewVif, not dVifReset: only the former assigns nVif[idx].idx,
			// and VifUnpackNEON_Dynarec::SetMasks/writeBackRow resolve MTVU_VifX
			// through it. Left at its zero-initialized value, a VIF1 unpack reads
			// VIF0's row/col registers.
			resetNewVif(c.idx);
			if (c.idx)
				dVifUnpack<1>(data.data(), isFill);
			else
				dVifUnpack<0>(data.data(), isFill);
			break;
	}

	RunResult out;
	out.mem.resize(VuMemSize(c.idx));
	std::memcpy(out.mem.data(), VuMem(c.idx), out.mem.size());
	out.row = Vif(c.idx).MaskRow;
	return out;
}

// Compares VU memory word by word, skipping the W word of every quadword when
// the format's W lane is intentionally divergent (see header).
void ExpectMemEqual(const UnpackCase& c, const RunResult& expected, const RunResult& actual, const char* what)
{
	ASSERT_EQ(expected.mem.size(), actual.mem.size());
	const bool skip_w = HasDivergentWLane(c.fmt);

	const u32* e = reinterpret_cast<const u32*>(expected.mem.data());
	const u32* a = reinterpret_cast<const u32*>(actual.mem.data());
	const size_t words = expected.mem.size() / 4;

	int reported = 0;
	for (size_t i = 0; i < words; i++)
	{
		if (skip_w && (i & 3) == 3)
			continue;
		if (e[i] == a[i])
			continue;
		if (++reported > 8)
		{
			ADD_FAILURE() << what << ": more divergent words beyond the first 8";
			return;
		}
		ADD_FAILURE() << what << ": VU" << c.idx << " mem word " << i
					  << " (qw " << (i / 4) << " lane " << "XYZW"[i & 3] << ")"
					  << " expected 0x" << std::hex << e[i] << " got 0x" << a[i] << std::dec;
	}
}

// ---------------------------------------------------------------------------

// Generates the nVifUpk[] table that _nVifUnpack dispatches through. VMManager
// does this at startup; the recompiler harness does not, so every suite here has
// to make sure it has happened. Not just the suites that call _nVifUnpack
// directly: dVifUnpack falls back to it for out-of-bounds transfers, and a
// missing table shows up there as a call through a null pointer.
void EnsureVifUnpackReady()
{
	static bool ready = false;
	if (ready)
		return;
	VifUnpackSSE_Init();
	resetNewVif(0);
	resetNewVif(1);
	ready = true;
}

class VifUnpackTest : public ::testing::TestWithParam<UnpackCase>
{
protected:
	void SetUp() override
	{
		ASSERT_TRUE(recompiler_tests::RecompilerTestEnvironment::IsReady())
			<< "RecompilerTestEnvironment must be initialized by main()";
		EnsureVifUnpackReady();
	}
};

TEST_P(VifUnpackTest, NeonPathsMatchScalarOracle)
{
	const UnpackCase& c = GetParam();

	const u8 vSize = nVifT[MakeCmd(c.fmt, c.masked) & 0x0f];
	ASSERT_GT(vSize, 0) << "format has no source-size entry";
	const std::vector<u8> data = MakeSourceData(static_cast<size_t>(c.num) * vSize);

	const RunResult expected = RunPath(c, data, Path::Reference);
	const RunResult neon = RunPath(c, data, Path::InterpreterNeon);
	const RunResult dyn = RunPath(c, data, Path::Dynarec);

	ExpectMemEqual(c, expected, neon, "interpreter NEON (VifUnpackNEON_Simple)");
	ExpectMemEqual(c, expected, dyn, "dynarec (VifUnpackNEON_Dynarec)");

	// MODE 2 and 3 write the row register back; 0 and 1 must leave it alone.
	// Checked for every case so an unintended write-back is caught too.
	for (int i = 0; i < 4; i++)
	{
		EXPECT_EQ(expected.row._u32[i], dyn.row._u32[i])
			<< "dynarec MaskRow lane " << i << " after mode " << c.mode;
	}
}

// The case list is organised by the failure each group would catch, not by
// enumerating the cross product — a full sweep of format x mask x mode x cycle
// is thousands of combinations that mostly re-test the same lane logic.
const UnpackCase kCases[] = {
	// 1. Per-format data expansion, unmasked, mode 0. This is where sign vs zero
	//    extension (usn), V2's v1v0v1v0 duplication and V4_5's RGBA5551 bit
	//    spreading live. Both signedness values for every sub-32-bit format.
	{"S32",         1, S_32,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"S16_signed",  1, S_16,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"S16_unsigned",1, S_16,  false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"S8_signed",   1, S_8,   false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"S8_unsigned", 1, S_8,   false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"V2_32",       1, V2_32, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V2_16_signed",1, V2_16, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V2_16_uns",   1, V2_16, false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"V2_8_signed", 1, V2_8,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V2_8_uns",    1, V2_8,  false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"V3_32",       1, V3_32, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V3_16_signed",1, V3_16, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V3_8_signed", 1, V3_8,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_32",       1, V4_32, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_16_signed",1, V4_16, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_16_uns",   1, V4_16, false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_8_signed", 1, V4_8,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_8_uns",    1, V4_8,  false, 1, 4, 1, 1, 0, 0, 0x000, 0},
	{"V4_5",        1, V4_5,  false, 0, 4, 1, 1, 0, 0, 0x000, 0},

	// 2. Masking. mask is 2 bits per lane per cycle: 0 data, 1 row, 2 col,
	//    3 write-protect. The col case must index by cycle, and write-protect
	//    must leave the fill pattern intact — both are easy to get wrong in a
	//    lane-merge transcription.
	{"mask_all_data",    1, V4_32, true, 0, 4, 1, 1, 0, 0x00000000u, 0x000, 0},
	{"mask_all_row",     1, V4_32, true, 0, 4, 1, 1, 0, 0x55555555u, 0x000, 0},
	{"mask_all_col",     1, V4_32, true, 0, 4, 1, 1, 0, 0xAAAAAAAAu, 0x000, 0},
	{"mask_all_protect", 1, V4_32, true, 0, 4, 1, 1, 0, 0xFFFFFFFFu, 0x000, 0},
	// One of each code in x/y/z/w, and a different arrangement per cycle so a
	// generator that ignored the cycle index would be caught.
	{"mask_mixed",       1, V4_32, true, 0, 8, 1, 1, 0, 0xE4B11B4Eu, 0x000, 0},
	{"mask_mixed_4cyc",  1, V4_32, true, 0, 8, 4, 4, 0, 0x1B4EE4B1u, 0x000, 0},
	{"mask_mixed_v4_8",  1, V4_8,  true, 1, 8, 1, 1, 0, 0xE4B11B4Eu, 0x000, 0},

	// 3. MODE. 1 adds the row, 2 adds and writes the row back, 3 replaces the
	//    row with the data. Also crossed with masking, since doMaskWrite folds
	//    the mode merge and the mask merge into one lane computation.
	{"mode1_offset",       1, V4_32, false, 0, 4, 1, 1, 1, 0, 0x000, 0},
	{"mode2_difference",   1, V4_32, false, 0, 4, 1, 1, 2, 0, 0x000, 0},
	{"mode3_setrow",       1, V4_32, false, 0, 4, 1, 1, 3, 0, 0x000, 0},
	{"mode1_masked",       1, V4_32, true,  0, 8, 1, 1, 1, 0xE4B11B4Eu, 0x000, 0},
	{"mode2_masked",       1, V4_32, true,  0, 8, 1, 1, 2, 0xE4B11B4Eu, 0x000, 0},
	{"mode3_masked",       1, V4_32, true,  0, 8, 1, 1, 3, 0xE4B11B4Eu, 0x000, 0},
	{"mode1_s32",          1, S_32,  false, 0, 4, 1, 1, 1, 0, 0x000, 0},
	{"mode2_v4_8",         1, V4_8,  false, 1, 4, 1, 1, 2, 0, 0x000, 0},

	// 4. CYCLE. cl > wl skips forward in VU memory between write blocks; cl < wl
	//    repeats source data to fill. Both change the addressing arithmetic the
	//    dynarec bakes into its unrolled loop.
	{"skip_2_1",   1, V4_32, false, 0, 8,  2, 1, 0, 0, 0x000, 0},
	{"skip_4_2",   1, V4_32, false, 0, 8,  4, 2, 0, 0, 0x000, 0},
	{"skip_4_3",   1, V4_32, false, 0, 9,  4, 3, 0, 0, 0x000, 0},
	{"fill_1_2",   1, V4_32, false, 0, 8,  1, 2, 0, 0, 0x000, 0},
	{"fill_2_4",   1, V4_32, false, 0, 8,  2, 4, 0, 0, 0x000, 0},
	{"fill_masked",1, V4_32, true,  0, 8,  1, 2, 0, 0xE4B11B4Eu, 0x000, 0},
	{"skip_masked",1, V4_32, true,  0, 8,  4, 2, 0, 0xE4B11B4Eu, 0x000, 0},
	{"fill_v4_8",  1, V4_8,  false, 1, 8,  1, 2, 0, 0, 0x000, 0},

	// 5. num boundaries. num is a u8 field where 0 means 256, and wl=0 likewise
	//    means 256 (the KH2 case dVifUnpack comments on).
	{"num_1",      1, V4_32, false, 0, 1,   1, 1, 0, 0, 0x000, 0},
	{"num_255",    1, V4_32, false, 0, 255, 1, 1, 0, 0, 0x000, 0},
	{"num_256",    1, V4_32, false, 0, 256, 1, 1, 0, 0, 0x000, 0},
	{"wl_0_is_256",1, V4_32, false, 0, 8,   1, 0, 0, 0, 0x000, 0},

	// 6. Non-zero write cursors, including one that wraps the VU1 address mask.
	{"addr_offset",   1, V4_32, false, 0, 8, 1, 1, 0, 0, 0x120, 0},
	{"addr_high",     1, V4_32, false, 0, 8, 1, 1, 0, 0, 0x3000, 0},

	// 7. VIF0, whose VU memory is a quarter the size and uses a different
	//    address mask. Nothing else in the suite touches idx 0.
	{"vif0_v4_32",  0, V4_32, false, 0, 4, 1, 1, 0, 0, 0x000, 0},
	{"vif0_masked", 0, V4_32, true,  0, 4, 1, 1, 0, 0xE4B11B4Eu, 0x000, 0},
	{"vif0_mode2",  0, V4_32, false, 0, 4, 1, 1, 2, 0, 0x000, 0},
	{"vif0_skip",   0, V4_32, false, 0, 8, 2, 1, 0, 0, 0x000, 0},

	// 8. Every write-lane subset, one case each.
	//
	//    The dynarec does not store a masked quadword with one instruction. It
	//    selects, from a sixteen-way switch, a hand-written sequence that touches
	//    only the lanes this cycle actually writes — and those sequences differ
	//    in kind, not just in offset: a full-width store for X+Y, a 64-bit lane
	//    store for Z+W, per-lane stores with hand-computed byte offsets for the
	//    scattered subsets, and a post-indexed pair for Y+Z. Each one is an
	//    independent opportunity to name the wrong lane or the wrong offset.
	//
	//    The subset is chosen by which lanes carry the write-protect code, so a
	//    mask naming three protected lanes reaches the single-lane store. The
	//    cases already above happen to land only on the three-lane subsets;
	//    these reach the other ten. Protected lanes must come back holding the
	//    fill pattern and written lanes the unpacked data, so a sequence that
	//    stores to a neighbouring lane fails on both halves at once.
	{"write_x",  1, V4_32, true, 0, 4, 1, 1, 0, 0xFCFCFCFCu, 0x000, 0},
	{"write_y",  1, V4_32, true, 0, 4, 1, 1, 0, 0xF3F3F3F3u, 0x000, 0},
	{"write_z",  1, V4_32, true, 0, 4, 1, 1, 0, 0xCFCFCFCFu, 0x000, 0},
	{"write_w",  1, V4_32, true, 0, 4, 1, 1, 0, 0x3F3F3F3Fu, 0x000, 0},
	{"write_xy", 1, V4_32, true, 0, 4, 1, 1, 0, 0xF0F0F0F0u, 0x000, 0},
	{"write_xz", 1, V4_32, true, 0, 4, 1, 1, 0, 0xCCCCCCCCu, 0x000, 0},
	{"write_xw", 1, V4_32, true, 0, 4, 1, 1, 0, 0x3C3C3C3Cu, 0x000, 0},
	{"write_yz", 1, V4_32, true, 0, 4, 1, 1, 0, 0xC3C3C3C3u, 0x000, 0},
	{"write_yw", 1, V4_32, true, 0, 4, 1, 1, 0, 0x33333333u, 0x000, 0},
	{"write_zw", 1, V4_32, true, 0, 4, 1, 1, 0, 0x0F0F0F0Fu, 0x000, 0},

	// The same selector again with a mode active, because doMaskWrite folds the
	// mode merge and the mask merge into one lane computation before choosing
	// the store: with lanes protected, the mode merge runs on a partial lane set
	// rather than the whole register, which is a different code path from the
	// unmasked mode cases in group 3.
	{"write_yz_mode1", 1, V4_32, true, 0, 4, 1, 1, 1, 0xC3C3C3C3u, 0x000, 0},
	{"write_x_mode2",  1, V4_32, true, 0, 4, 1, 1, 2, 0xFCFCFCFCu, 0x000, 0},
};

INSTANTIATE_TEST_SUITE_P(
	VifUnpack, VifUnpackTest, ::testing::ValuesIn(kCases),
	[](const ::testing::TestParamInfo<UnpackCase>& info) { return std::string(info.param.name); });

// ---------------------------------------------------------------------------

// The one W-lane fact that is checkable without re-deriving the generators'
// iteration arithmetic: an aligned V2_32 unpack zeroes W. Both generators do it
// ("zero last word - tested on ps2"), and the x86 SSE generator agrees, so a
// NEON transcription that dropped the Ins(wzr) would be a real regression that
// the oracle comparison above deliberately cannot see.
TEST(VifUnpackAligned, AlignedV2_32ZeroesWLane)
{
	ASSERT_TRUE(recompiler_tests::RecompilerTestEnvironment::IsReady());
	EnsureVifUnpackReady();

	UnpackCase c{"aligned_v2_32", 1, V2_32, false, 0, 4, 1, 1, 0, 0, 0x000, /*start_aligned=*/1};
	const std::vector<u8> data = MakeSourceData(static_cast<size_t>(c.num) * nVifT[V2_32]);

	const RunResult dyn = RunPath(c, data, Path::Dynarec);

	const u32* qw = reinterpret_cast<const u32*>(dyn.mem.data());
	for (u32 i = 0; i < c.num; i++)
	{
		EXPECT_EQ(0u, qw[i * 4 + 3]) << "aligned V2_32 quadword " << i << " W lane should be zeroed";
		// X/Y must still carry data — guards against the whole write being lost.
		EXPECT_NE(0u, qw[i * 4 + 0] | qw[i * 4 + 1]) << "quadword " << i << " lost its data";
	}
}

// dVifUnpack falls back to _nVifUnpack when the write would run past the end of
// VU memory, rather than letting the compiled routine scribble out of bounds.
// The fallback is a plain branch, but it is the only thing standing between an
// oversized transfer and memory corruption, so it is worth pinning.
TEST(VifUnpackWrap, OversizedTransferFallsBackToInterpreter)
{
	ASSERT_TRUE(recompiler_tests::RecompilerTestEnvironment::IsReady());
	EnsureVifUnpackReady();

	// 64 quadwords starting 16 bytes from the end of VU1 memory: the block
	// length far exceeds what remains, so the bounds check must reject it.
	UnpackCase c{"wrap", 1, V4_32, false, 0, 64, 1, 1, 0, 0, 0x3FF0, 0};
	const std::vector<u8> data = MakeSourceData(static_cast<size_t>(c.num) * nVifT[V4_32]);

	const RunResult expected = RunPath(c, data, Path::Reference);
	const RunResult dyn = RunPath(c, data, Path::Dynarec);

	// Taking the fallback means the result is the interpreter's, which is what
	// the oracle models — including the address wrap back to the start.
	ExpectMemEqual(c, expected, dyn, "dynarec wrap fallback");
}

// A cycle whose four lanes are all write-protected has nothing to store, and the
// compiler drops the whole body for it rather than emitting a store of no lanes.
// The differential case above (mask_all_protect) would pass either way, since a
// generator that wrote something wrong and an oracle that wrote nothing only have
// to agree with each other — and here they cannot, because the oracle writes
// nothing at all. So this asserts the absolute fact instead: VU memory comes back
// byte-identical to the fill pattern.
//
// It also pins the guard behind it. The store selector has a case for "no lanes"
// that only logs an error, and it is reachable only if this skip stops working.
TEST(VifUnpackMask, FullyProtectedBlockWritesNothing)
{
	ASSERT_TRUE(recompiler_tests::RecompilerTestEnvironment::IsReady());
	EnsureVifUnpackReady();

	UnpackCase c{"all_protect", 1, V4_32, true, 0, 8, 1, 1, 0, 0xFFFFFFFFu, 0x000, 0};
	const std::vector<u8> data = MakeSourceData(static_cast<size_t>(c.num) * nVifT[V4_32]);

	// The pattern RunPath seeds before it dispatches, to compare against.
	FillVuMemPattern(c.idx);
	std::vector<u8> untouched(VuMemSize(c.idx));
	std::memcpy(untouched.data(), VuMem(c.idx), untouched.size());

	const RunResult dyn = RunPath(c, data, Path::Dynarec);

	ASSERT_EQ(untouched.size(), dyn.mem.size());
	EXPECT_EQ(0, std::memcmp(untouched.data(), dyn.mem.data(), untouched.size()))
		<< "a fully write-protected unpack must leave VU memory alone";
}

} // namespace
